
name: "Count Errors"
description: "Count the number of errors found by Kube-linter"
author: "dhrvsingh29@gmail.com"

inputs:
  Log File:
    description: "name of the downloaded artifact"
    required: true
    default: "kubelinter.log"

runs:
  using: "composite"
  steps:
    - run: python --version
      shell: bash
   
