name: A workflow for my Hello World file
on: push
jobs:
  install-runner:
    runs-on: ubuntu-20.04
    name: Install runner
    steps:
      - name: Authenticate
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_USER: ${{ secrets.OPENSHIFT_USER }}
          OPENSHIFT_NAMESPACE: default
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: default
      - name: Install self hosted runner into this repository
        uses: redhat-actions/openshift-actions-runner-installer@v1
        with:
          github_pat: ${{ secrets.PAT }}
  self-hosted-workflow :
    name: Running on OpenShift runner
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Scan valid yaml with kube-linter
        uses: stackrox/kube-linter-action@v1.0.2
        with:
          directory: sample/invalid-yaml
      - uses: actions/checkout@v1
      - uses: ./action-a
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' recieved from '${{github.event.client_payload.repository }}'"
      - name: Return back to the original repo
        if: github.event.action == 'ping'
        run: |
          curl -X POST https://api.github.com/repos/dev0701/github_actions_and_apps_demo/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.WORKFLOW_SECRET }} \
          --data '{"event_type": "return", "client_payload": {"repository": "'"$GITHUB_REPOSITORY"'" }}'
      

