name: A workflow for my Hello World file
on:
 pull_request:
  branches: [main]
jobs:
  install-runner-default:
    runs-on: ubuntu-20.04
    name: Install runner on openshift cluster
    steps:
      - name: Authenticate
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_USER: ${{ secrets.OPENSHIFT_USER }}
          OPENSHIFT_NAMESPACE: default
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: default
      - name: Install self hosted runner into this repository
        uses: redhat-actions/openshift-actions-runner-installer@v1
        with:
          github_pat: ${{ secrets.PAT }}
          runner_image: icr.io/gitsecure/microscope-scanner:1.0.0
      - name: Install CLI tools from OpenShift Mirror
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "mirror"
          oc: "3"
          helm: "latest"
          
  run-kube-linter :
    name: Running Kube-Linter on a set of .yaml files
    needs: install-runner-default
    runs-on: [default-runner]
    steps:      
      - uses: actions/checkout@v2
      - name: Scan valid yaml with kube-linter
        uses: stackrox/kube-linter-action@v1.0.2
        with:
          directory: sample/invalid-yaml
          
  print-log :
    name: Print the linter log file
    needs: run-kube-linter
    runs-on: [default-runner]     
    steps:   
      - shell: bash
        run: |
             cat kubelinter.log
  save-log-if-kubelinter-fails :
    name: Save the log as an artifact if linting errors exist
    needs: run-kube-linter
    runs-on: [default-runner]     
    if: always() && (needs.run-kube-linter.result == 'failure')
    steps:   
      - name: Upload log file
        uses: actions/upload-artifact@v2
        with:
          name: 'Kube-linter log'
          path: kubelinter.log
          
#  run-python-script :
#   name: Check the number of errors found by Kube-linter
#   needs: save-log-if-kubelinter-fails
#   runs-on: [self-hosted]
#   if: always() && (needs.save-log-if-kubelinter-fails.result == 'success')
#   steps:
#      - name: Download log file
#        uses: actions/download-artifact@v2
#        with:
#          name: 'Kube-linter log'
#      - name: Checkout repo
#        uses: actions/checkout@v1
#      - name: Run custom action to install python
#        uses: ./action-a
